# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jeopardy! The Complete Saga' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jeopardy! The Complete Saga
  pod 'Firebase/Firestore'

  target 'Jeopardy! The Complete SagaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Jeopardy! The Complete SagaUITests' do
    # Pods for testing
  end

end
